export * from "./CallToAction";
export * from './HowItWorks';
export * from "./Hero";
export * from "./LogoTicker";
export * from "./Pricing";
export * from "./ProductShowcase";
export * from "./Testimonials";
export * from './WhyChoosePayDinner'
export * from './FAQ'